import { readFile, writeFile } from 'fs/promises';

const base = await readFile('output/001-anthropic-fullstack.html', 'utf8');

const variants = {
  'gitlab-ai-engineer': `AI product engineer with 8+ years building and shipping production software, applying for the Senior AI Engineer role at GitLab. As sole engineer behind PdfGPT.io, I grew an AI product to 100K+ users by integrating OpenAI and Claude APIs, designing RAG pipelines with semantic chunking and vector retrieval, and shipping agentic workflows end to end. I work fluently across Node.js, TypeScript, React and Next.js, and build REST and real-time APIs that scale. I am comfortable with prompt engineering and wiring LLMs into real business workflows, exactly the foundation GitLab needs to embed AI across DevSecOps. GitLab's all-remote culture and Bangalore-based hiring fit how I already work: high ownership, asynchronous, and shipping daily. I would bring product-minded AI engineering to a platform trusted by more than 50 million developers.`,

  'turing-genai-engineer': `Generative AI engineer with 8+ years of software experience, applying for the Senior Gen AI Engineer role at Turing. I sit at exactly the intersection Turing describes: I build AI agents and RAG systems in production, having grown PdfGPT.io to 100K+ users as sole engineer with semantic chunking, embeddings, vector retrieval and agentic workflows over OpenAI and Claude. I design retrieval pipelines that reason over large document corpora and enrich answers with live context, and I work hands-on with agent frameworks and vector stores. Beyond the AI layer I own the full stack in Node.js, TypeScript, React and Next.js, so I can take agentic systems from prototype to reliable service. Turing's mission to deploy advanced AI into mission-critical enterprise workflows maps directly to what I have shipped solo. I would bring builder velocity and 8 years of delivery to Turing's GenAI team.`,

  'deepgram-voice-agents': `Full-stack AI engineer with 8+ years shipping production software, applying for the Software Engineer, Voice Agents / AI role at Deepgram. Voice agents are squarely in my wheelhouse: I build voice AI agents and conversational systems, and as sole engineer of PdfGPT.io I integrated OpenAI and Claude with RAG pipelines and real-time features for 100K+ users. I work daily with real-time APIs, WebSockets and low-latency Node.js backends, the exact primitives behind production voice agents and Deepgram's speech-to-text and text-to-speech stack. I am product-minded and AI-first, comfortable experimenting with and building my own AI tooling into my workflow, which matches Deepgram's operating rhythm. Deepgram for Restaurants blends real-world deployment with voice intelligence, where my zero-to-one instincts and full-stack depth would let me ship customer-facing features fast. I would love to help build the voice AI economy at Deepgram.`,

  'postman-product-trust': `Full-stack engineer with 8+ years building production software, applying for the Software Engineer (Fullstack, frontend-heavy), Product Trust role at Postman in Bengaluru. I founded and scaled PdfGPT.io to 100K+ users as sole engineer, owning the full stack in React, Next.js, TypeScript and Node.js with a strong eye for frontend performance (LCP, CLS) and clean, trustworthy user experiences. Product Trust's mandate to keep Postman safe and trusted resonates with how I build: I have shipped authentication, Stripe billing and secure data flows for a platform handling sensitive user documents at scale. I bridge customer-facing product thinking with hands-on engineering, exactly the conduit role Product Trust describes. Based in Ahmedabad, I am ready to contribute from Postman's Bangalore home base with full timezone overlap. I would bring builder velocity and frontend depth to a platform used by 45 million developers.`,

  'postman-customer-journey': `Senior full-stack engineer with 8+ years building and growing software products, applying for the Senior Fullstack Software Engineer role on Postman's Customer Journey team. Growth and onboarding are my proven strength: I grew PdfGPT.io from zero to 100K+ users organically as sole engineer, designing the entire sign-up, activation and monetization funnel with Stripe free trials and paid plans. I own the full stack in React, Next.js, TypeScript and Node.js, and I optimize the exact first-interaction-to-purchase paths the Customer Journey team shapes. My product sense comes from living the full lifecycle of a product I built, scaled and monetized myself. Postman's mission to simplify the API lifecycle for 45 million developers is the kind of scale where small onboarding improvements compound enormously. I would bring growth-engineering instincts and 8 years of delivery to the team.`,
};

const re = /(<div class="summary-text">)([\s\S]*?)(<\/div>)/;

for (const [slug, summary] of Object.entries(variants)) {
  if (!re.test(base)) throw new Error('summary-text block not found');
  const out = base.replace(re, `$1\n      ${summary}\n    $3`);
  const path = `output/cron-${slug}.html`;
  await writeFile(path, out, 'utf8');
  console.log('wrote', path);
}
